# fly.toml app configuration file generated for polymarket-bots on 2026-01-08

app = "polymarket-bots-farzad"
primary_region = "ams"

[build]

[env]
  PYTHONPATH = "."
  PYTHONUNBUFFERED = "1"

[processes]
  safe = "python3 -m agents.application.pyml_trader"
  scalper = "python3 pyml_ws_scalper.py --live"
  api = "uvicorn api:app --host 0.0.0.0 --port 8000"
  copy = "python3 pyml_copy_trader.py"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["api"]

[[vm]]
size = "shared-cpu-1x"
memory = "512mb"
cpus = 1
